name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: braidai
  GAR_LOCATION: us-central1
  FRONTEND_SERVICE: braidai-frontend
  BACKEND_SERVICE: braidai-backend
  REPOSITORY: braidai-repo

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/362912017141/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@braidai.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Build and push the backend service using a robust action
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./agent-python-backend
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }}

      # Build and push the frontend service using a robust action
      # Build and push the frontend service
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./agent-frontend
          push: true
          build-args: VITE_API_BASE_URL=https://braidai-backend-362912017141.us-central1.run.app
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FRONTEND_SERVICE }}:${{ github.sha }}
          
      - name: Deploy Backend to Cloud Run
        run: |-
          gcloud run deploy ${{ env.BACKEND_SERVICE }} \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }} \
            --region ${{ env.GAR_LOCATION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8000

      - name: Deploy Frontend to Cloud Run
        run: |-
          gcloud run deploy ${{ env.FRONTEND_SERVICE }} \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FRONTEND_SERVICE }}:${{ github.sha }} \
            --region ${{ env.GAR_LOCATION }} \
            --platform managed \
            --allow-unauthenticated
